source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Poc.Mauro.Bianchelli' do
   
   pod 'Moya', '~> 11.0'
   pod 'RxSwift',    '~> 4.0'
   pod 'RxCocoa',    '~> 4.0'
   pod 'lottie-ios'
end


